### ISSUE TITLE
[QUESTION] Would Flysystem suffice as File-System-Abstraction?

### ISSUE THREAD

**Issue by potherca** [rkrx/php-contracts#4]
The wishlist states "File-System-Abstraction"

[FlySystem](http://flysystem.thephpleague.com/) is becoming the de-facto file system abstraction package for remote file systems (although it also has a connector for the local filesystem).

Would the interfaces from this library be worth mentioning?

https://github.com/thephpleague/flysystem/blob/HEAD/src/ReadInterface.php
https://github.com/thephpleague/flysystem/blob/HEAD/src/FilesystemInterface.php

**Comment by rkrx** [comment]
Thank you. I've added FlySystem under [Noteworthy projects](https://github.com/rkrx/php-contracts#noteworthy-projects). See commit [1cee3d1](https://github.com/rkrx/php-contracts/commit/1cee3d1f4dadf6f3a2db9b51b8fcaf5d4413f4d9).

**Comment by potherca** [comment]
Cool! :+1:
